### ISSUE TITLE
unable to add new docker containers

### ISSUE THREAD

**Issue by taprindl** [AxelPina/portainer-traefik-letsencrypt#1]
I've used your script and everything works properly, but I'm trying to expose an instance of nginx, what labels are needed to do this and also get it to generate the SSL automatically?

Thanks!

**Comment by axelpina** [comment]
Hi, sorry for the late response. If you wish to do the same but with nginx, could check out the [Deploying Portainer behind nginx reverse proxy documentation](https://docs.portainer.io/v/ce-2.6/advanced/reverse-proxy/nginx). I genuinely haven't tried it with Nginx but at the top of my head you'd probably need to create a container with certbot so it can deploy the let's encrypt SSL and renew it automatically itself.

Hope this helps.

**Comment by taprindl** [comment]
Hey Alex,

Thank you for the response, I actually just figured this out. I just wasn't putting the correct labels on the container, these are the labels I used in case anyone else has this issue:

traefik.enable=true
traefik.http.routers.nginx.rule=Host(`nginx.website.com`)
traefik.http.routers.nginx.tls=true
traefik.http.routers.nginx.tls.certresolver=letsencrypt

Thanks Alex!
