### ISSUE TITLE
nginx-proxy-manager-app stopped

### ISSUE THREAD

**Issue by fdstevex** [AxelPina/portainer-traefik-letsencrypt#2]
Hey, this is pretty much exactly what I was looking for for a simple front end for deploying some development containers.

Ran into a problem after starting it though, the nginx-proxy-manager-app container is stopped with an error.

Log is attached, but the end of it is:

```
[5/4/2022] [11:01:29 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[5/4/2022] [11:01:29 AM] [SSL      ] › ℹ  info      Renew Complete
`QueryBuilder#allowEager` method is deprecated. You should use `allowGraph` instead. `allowEager` method will be removed in 3.0
`QueryBuilder#eager` method is deprecated. You should use the `withGraphFetched` method instead. `eager` method will be removed in 3.0
QueryBuilder#omit is deprecated. This method will be removed in version 3.0
Model#$omit is deprected and will be removed in 3.0.
[5/4/2022] [11:03:48 AM] [Nginx    ] › ℹ  info      Reloading Nginx
s6-svscanctl: fatal: unable to control /var/run/s6/services: supervisor not listening
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

[_nginx-proxy-manager-app-1_logs.txt](https://github.com/AxelPina/portainer-traefik-letsencrypt/files/8619757/_nginx-proxy-manager-app-1_logs.txt)

Thanks

**Comment by axelpina** [comment]
Hey @fdstevex I apologize for the very late reply. I have not updated nor worked with this repo in a long while. I am unable to help you troubleshoot this on nginx. However if you solved this issue feel free to post your solution for others presenting the same issue.
